server:
  port:
    8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your-database
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your_username
    password: your_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: your-api-prefix
jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  secretKey: your-secret-key