# remove 'example' from filename
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 20
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: your-api-prefix
jwt:
  expiration: 2592000 # 30 days = 30 * 24 * 60 * 60
  secretKey: your-secret-key
pagination:
  default-page-size: 10
  max-page-size: 100
# your cors config
cors:
  allowed-origins: "http://localhost:3002"
  api-path: "/api/**"