# remove 'example' from filename
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your-database?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: your_username
    password: your_password

cloudinary:
  cloud_name: your_cloud_name
  api_key: your_api_key
  api_secret: your_api_secret

